### ISSUE TITLE
I am disappoint

### ISSUE THREAD

**Issue by voltrevo** [IonicaBizau/pi-number#6]
```
> pi(16, false)
'141592653589793'
// correct
> pi(17, false)
'14158639510370614'
//   ^ incorrect
```

**Comment by IonicaBizau** [comment]
@voltrevo Yes, because it's just an approximation in the end. Contributions are welcome, though!

If you want to contribute, I'd be happy to merge pull requests! :sparkle:

**Comment by IonicaBizau** [comment]
Fixed in `2.x.x`
