### ISSUE TITLE
Feature Request: Accurate fallback file

### ISSUE THREAD

**Issue by TheJaredWilcurt** [IonicaBizau/pi-number#9]
Math in JS is not the most accurate. However people may want an actually accurate value returned to them.

You could create a fallback file that contains a large set of pi (1,000 digits? 1,000,000?) then allow for an option to pass in the string 'offline' or 'accurate' or 'precalculated'. This would then read in that file from the file system, store the contents of the file to a string and then just perform a substring to get the value to return to the user.

```js
function precalculated (amountToReturn, skipThreeDot) {
    var fs = require('fs');
    var data = '';
    if (amountToReturn > 1000) {
        data = fs.readFileSync('million-digits-of-pi.txt');
    } else {
        data = fs.readFileSync('thousand-digits-of-pi.txt');
    }
    data = data.toString();
    data = data.trim();

    var amountToSkip = 0;
    if (skipThreeDot) {
        amountToSkip = 2;
    }

    return data.substring(amountToSkip, amountToSkip + amountToReturn);
}
```

This will be useful for people that need more accurate versions of Pi, or want to offset CPU time for storage space.

**Comment by IonicaBizau** [comment]
That's a good idea! ✨

**Comment by TheJaredWilcurt** [comment]
I added in the `data = data.toString();` line just now. Forgot about that, otherwise you'd get back buffer stream of data.

**Comment by IonicaBizau** [comment]
Fixed in `2.x.x`
